services:
  hello-ubuntu:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
      target: ubuntu-runner

  hello-alpine:
     build:
      context: .
      dockerfile: alpine.Dockerfile
      target: alpine-runner